### ISSUE TITLE
Incorrect behaviour of jamming in floating-point addition

### ISSUE THREAD

**Issue by Theodor-Lindberg** [apytypes/apytypes#245]
The early exit check in floating-point addition makes jamming to behave incorrectly when adding with zero.

```Python
with QuantizationContext(QuantizationMode.JAM):
    # Becomes APyFloat(sign=0, exp=15, man=0, exp_bits=5, man_bits=2)
    # Should be APyFloat(sign=0, exp=15, man=1, exp_bits=5, man_bits=2)
    APyFloat(0, 15, 0, 5, 2) + APyFloat(0, 0, 0, 5, 2)
```

**Comment by oscargus** [comment]
Maybe one should check that quantization mode is not jamming as well?

**Comment by Theodor-Lindberg** [comment]
Yes that would probably solve it.

**Comment by oscargus** [comment]
I have a PR related to this in the pipe.

**Comment by oscargus** [comment]
Although one should really ask oneself if e.g. multiplication by zero should be jammed...

**Comment by miklhh** [comment]
As of #574, the jamming bit is properly applied to all floating-point operations when the quantization mode is `JAMMING`. There are however two intentional special cases when the jamming bit is not applied:

* During multiplication, the jamming bit is not applied if either operand is zero.
* During division, the jamming bit is not applied if the numerator is zero.

I'll close this issue with #574. Feel free to comment if the solution isn't satisfactory.
